databases:
- name: abdo123
  databaseName: dbabdo123
  user: abdo123
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: ZTele
  runtime: python
  repo: https://github.com/david66g/ZTele
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: abdo123
      property: connectionString
  - key: PYTHON_VERSION
    sync: false
  - key: TZ
    sync: false
  - key: TG_BOT_TOKEN
    sync: false
  - key: STRING_SESSION
    sync: false
  - key: ENV
    sync: false
  - key: APP_ID
    sync: false
  - key: API_HASH
    sync: false
  - key: ALIVE_NAME
    sync: false
  region: frankfurt
  buildCommand: pip install -r requirements.txt
  startCommand: python3 server.py & python3 -m zlzl
  autoDeployTrigger: commit
version: "1"
